name: Linux Test

on:
  push:
    tags:
      - v1.**
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  #### x64 LINUX build ####
  build-linux64:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: create submodule status file
      run: git submodule status > submodule_status

    - name: Restore ffmpeg cache
      id: cache-ffmpeg
      uses: actions/cache@v3
      env:
        cache-name: cache-ffmpeg-build
      with:
        path: ${{github.workspace}}/ffmpeg/lib_lin_x64
        key: ${{runner.os}}-build-${{env.cache-name}}-${{hashFiles('submodule_status,ffmpeg/build-scripts/**')}}

    - if: ${{ steps.cache-ffmpeg.outputs.cache-hit != 'true' }}
      name: Build ffmpeg
      run: |
        git submodule init
        git submodule update
        sudo apt-get update
        sudo apt-get install -y yasm
        pushd ffmpeg/build-scripts
        ./build_ffmpeg.sh
        popd

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        install-deps: 'true'
        cache: 'true'
        cache-key-prefix: 'install-qt-action-x64-linux'

    - name: Configure CMake
      run: >
        cmake
        -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install
        -DRPSB_MAKE_PLUGIN_FILE=OFF

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target install

    - name: Archive raw files
      uses: actions/upload-artifact@v3
      with:
        name: linux-x64
        path: ${{github.workspace}}/install/
        if-no-files-found: error
  